### ISSUE TITLE
application-template

### ISSUE THREAD

**Issue by Marshal78** [sabre1041/openshift-flexvolume-cifs#2]
Hi!
Is it an error "value" field in part of application-template.yml:
description: Name of the secret containing the CIFS credentials.
  displayName: CIFS Secret
  name: SECRET
  required: true
  value: "file_mode=0770,dir_mode=0770"
I think it should be "cifs-credentials" instead of "file_mode=0770,dir_mode=0770"

**Comment by sabre1041** [comment]
@Marshal78 thanks for calling out this issue!

Corrected in f106a0bb7c66960af38d0b5b5334aa145f2dc7e8
